"""empty message

Revision ID: 8ee38a15d32f
Revises: 
Create Date: 2024-01-03 13:08:05.748466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee38a15d32f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('bookName', sa.String(length=50), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bookId')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('studentClass', sa.String(length=50), nullable=False),
    sa.Column('permanentAddress', sa.String(length=100), nullable=True),
    sa.Column('correspondsAddress', sa.String(length=100), nullable=True),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subject',
    sa.Column('subId', sa.Integer(), nullable=False),
    sa.Column('subName', sa.String(length=50), nullable=False),
    sa.Column('createdOn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('subId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject')
    op.drop_table('student')
    op.drop_table('book')
    # ### end Alembic commands ###
